### ISSUE TITLE
Movie deleted after extract?

### ISSUE THREAD

**Issue by Nokoff** [RuudBurger/CouchPotatoServer#4403]
### Steps to reproduce:
1. .. Download movie with deluge
2. ..Movie gets picked up by couchpotato, seems to be extracted... then the movie vanishes (deleted???)

### Information:
Movie(s) I have this with: ... This.Is.Where.I.Leave.You.2014.BDRip.x264-COCAIN

Quality of the movie being searched: ...
Providers I use: ... Sceneaccess
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 0288cc88 (2014-12-22 23:02:05)
Running on: ... Unraid Docker

### Logs:
```
12-26 16:06:39  INFO [tato.core.plugins.renamer] Archive seems to be still copying/moving/downloading or just copied/moved/downloaded (created on Fri Dec 26 16:05:44 2014), ignoring for now: cocain.this.is.where.i.leave.you.2014.bdrip.x264.rar 
12-26 16:07:39  INFO [tato.core.plugins.renamer] Archive cocain.this.is.where.i.leave.you.2014.bdrip.x264.rar found. Extracting... 
12-26 16:12:13 ERROR [to.core.media._base.media] Media with id "28b01cffc0c84a99ad781868ea4b351a" not found 
12-26 16:12:13 ERROR [          couchpotato.api] Failed doing api request "dashboard.soon": Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/api.py", line 36, in run_handler
    res = api[route](**kwargs)
  File "/opt/couchpotato/couchpotato/core/plugins/dashboard.py", line 63, in getSoonView
    media = db.get('id', media_id)
  File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/opt/couchpotato/libs/CodernityDB/database.py", line 942, in get
    raise RecordNotFound(ex)
RecordNotFound: Location 'b39f0163acc14e36abfb02b46fa12ecc' not found 
12-26 16:12:13 ERROR [          couchpotato.api] Failed doing api request "notification.listener": Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/api.py", line 36, in run_handler
    res = api[route](**kwargs)
  File "/opt/couchpotato/couchpotato/core/notifications/core/main.py", line 280, in listener
    doc = db.get('id', n.get('_id'))
  File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/opt/couchpotato/libs/CodernityDB/database.py", line 942, in get
    raise RecordNotFound(ex)
RecordNotFound: Location '4b302d89124f4b4ea2c65e391d15f468' not found 
12-26 16:12:14 ERROR [chpotato.core.plugins.log] API log: {'file': u'http://HOST/minified/head.js?1419583542', 'message': u"chrome 39: \nUncaught TypeError: Cannot read property 'length' of undefined", 'line': u'143', 'page': u'http://HOST/', '_request': <couchpotato.api.ApiHandler object at 0x2b6dde74bf10>} 
```

**Comment by RuudBurger** [comment]
Already in issues
