### ISSUE TITLE
Home tab fails to load. 

### ISSUE THREAD

**Issue by eli-jordan** [RuudBurger/CouchPotatoServer#4414]
### Steps to reproduce:
1. Open the 'Home' tab
2. See the below error in the logs, and the page fails to load
3. The page is stuck "Loading Snached and available"

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 0288cc88 (2014-12-23 08:02:05)
Running on: ...

### Logs:
```
12-28 22:56:03 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "/Users/admin/CouchPotatoServer/couchpotato/api.py", line 147, in sendData
    self.finish(result)
  File "/Users/admin/CouchPotatoServer/libs/tornado/web.py", line 866, in finish
    self.write(chunk)
  File "/Users/admin/CouchPotatoServer/libs/tornado/web.py", line 655, in write
    chunk = escape.json_encode(chunk)
  File "/Users/admin/CouchPotatoServer/libs/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 110: invalid start byte 
```

**Comment by oxeno** [comment]
Same thing for me (Home and Wanted pages), but i am not on master (using 2.6.1)

### Steps to reproduce:
1. Login to couchpotato
2. click home or click wanted
3. the spinner spins endlessly 

### Information:
Movie(s) I have this with: all
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: desktop: 2.6.1
Running on: windows 8.1

### Logs:
```
01-01 14:49:45 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "C:\Users\mediabox\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.1.win32\couchpotato\api.py", line 144, in taskFinished
  File "C:\Users\mediabox\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.1.win32\libs\tornado\web.py", line 655, in write
  File "C:\Users\mediabox\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.1.win32\libs\tornado\escape.py", line 88, in json_encode
  File "json\__init__.pyc", line 243, in dumps
  File "json\encoder.pyc", line 207, in encode
  File "json\encoder.pyc", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 106: invalid start byte 
```

**Comment by DcR-NL** [comment]
Started hapenning around a day ago, after my instalation downloaded a new release.

### Steps to reproduce:
1. Open the 'Home' tab.

### Result:
1. The page is stuck on "Loading Snached and available".

### Information:
Movie(s) I have this with: Fury
Quality of the movie being searched: 1080p
Providers I use: Torrentbytes, Torrentz, TorrentDay, ThePirateBay and KickassTorrents
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 0288cc88 (2014-12-22 22:02:05)
Running on: Synology NAS (Linux - x86)

### Logs:
```
01-02 13:37:49 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/api.py", line 147, in sendData
    self.finish(result)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/tornado/web.py", line 866, in finish
    self.write(chunk)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/tornado/web.py", line 655, in write
    chunk = escape.json_encode(chunk)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/tornado/escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "/usr/local/python/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 204: invalid start byte 
```

**Comment by sverr1** [comment]
Been having this issue two times now. At first it was because of a corrupted database and now, from what I've read it occurs when you snatch a torrent.

#4026 and several others, but posted my logs in that one.

**Comment by RuudBurger** [comment]
#4026

**Comment by eli-jordan** [comment]
I was able to resolve the issue by applying the fix suggested in this https://github.com/RuudBurger/CouchPotatoServer/issues/4377 bug report. Then deleting my database and reloading the existing movies
