### ISSUE TITLE
Failed checking snatched

### ISSUE THREAD

**Issue by erikkroes** [RuudBurger/CouchPotatoServer#4466]
### Steps to reproduce:
1. Not sure. It just happened while I wasn't paying attention but shows up every minute in my log now, and couchpotato won't copy anything anymore, doesn't even make ignore files.

### Information:
Providers I use: Kickass/piratebay
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 2f5526d5 (2015-01-02 18:54:36)
Running on: Up to date Ubuntu

### Logs:
```
01-05 18:14:14 ERROR [tato.core.plugins.renamer] Failed checking snatched: Traceback (most recent call last):
  File "/home/erik/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 923, in checkSnatched
    rels = list(fireEvent('release.with_status', ['snatched', 'seeding', 'missing'], single = True))
  File "/home/erik/CouchPotatoServer/couchpotato/core/plugins/release/main.py", line 539, in withStatus
    doc = db.get('id', ms['_id'])
  File "/home/erik/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/home/erik/CouchPotatoServer/libs/CodernityDB/database.py", line 949, in get
    data = storage.get(start, size, status)
  File "/home/erik/CouchPotatoServer/libs/CodernityDB/storage.py", line 139, in get
    return self.data_from(self._f.read(size))
  File "/home/erik/CouchPotatoServer/libs/CodernityDB/storage.py", line 114, in data_from
    return marshal.loads(data)
ValueError: bad marshal data (unknown type code) 
```

**Comment by RuudBurger** [comment]
Faulty database.
Shutdown CP and rename the `database` folder in the the data directory.
In the same data directory there is a `db_backup` folder with older databases you can put back.
