### ISSUE TITLE
Non-unicode letters in movie titles will not allow couchpotato to rename/find file

### ISSUE THREAD

**Issue by avluis** [RuudBurger/CouchPotatoServer#4472]
### Steps to reproduce:
1. Download/Ask for movie which title contains characters that may have issues with an OS.
2. Couchpotato will fail to rename, providers are supplying a title name not compatible with my system.

### Information:
Movie(s) I have this with: Aeon Flux
Quality of the movie being searched: Best (Blu-ray, 1080p)
Providers I use: Piratebay, KickAss Torrents, NZBMega Search with my own Spotweb install.
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 2f5526d5 (2015-01-02 11:54:36)
Running on: Synology DS1513+

### Logs:
```
01-06 00:16:17  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=aeon+flux&year=2005, data: [] 
01-06 00:16:17  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Aeon+Flux+2005/?limit=1, data: [] 
01-06 00:16:17  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?y=2005&t=aeon+flux, data: [] 
01-06 00:16:17  INFO [ie.providers.info.omdbapi] Found: Ăon Flux (2005) 
01-06 00:16:17  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/8202?api_key=xxx&append_to_response=alternative_titles, data: [] 
01-06 00:16:18  INFO [providers.info.themoviedb] Found: [u'\xc6on Flux (2005)'] 
01-06 00:16:18  INFO [tato.core.plugins.scanner] Found 1 movies in the folder /volume1/downloads/completed/movies 
01-06 00:16:18  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt0402022/, data: [] 
01-06 00:16:18  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?i=tt0402022, data: [] 
01-06 00:16:18  INFO [ie.providers.info.omdbapi] Found: Ăon Flux (2005) 
01-06 00:16:29 ERROR [31mError consuming task ListTask(Movie(/volume1/downloads/completed/movies/Aeon Flux 2005 1080p BluRay DTS x264.mkv), language_set([Language(English)]), podnapisi, ServiceConfig(True, /usr/local/couchpotatoserver/var/cache)) 
UNKNOWN UNKNOWN [31mError consuming task ListTask(Movie(/volume1/downloads/completed/movies/Aeon Flux 2005 1080p BluRay DTS x264.mkv), language_set([Language(English)]), subscenter, ServiceConfig(True, /usr/local/couchpotatoserver/var/cache)) 
UNKNOWN UNKNOWN [31mNo subtitles could be downloaded for video Movie(/volume1/downloads/completed/movies/Aeon Flux 2005 1080p BluRay DTS x264.mkv) 
01-06 00:16:31  INFO [tato.core.plugins.renamer] Moving "/volume1/downloads/completed/movies/Aeon Flux 2005 1080p BluRay DTS x264.mkv" to "/volume2/movies/Ăon Flux (2005) [HD]/Ăon Flux.mkv" 
01-06 00:16:31 ERROR [tato.core.plugins.renamer] Couldn't move file "/volume1/downloads/completed/movies/Aeon Flux 2005 1080p BluRay DTS x264.mkv" to "/volume2/movies/ÄÂon Flux (2005) [HD]/ÄÂon Flux.mkv": Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume2/movies/\xc3\x86on Flux (2005) [HD]/\xc3\x86on Flux.mkv' 
01-06 00:16:31 ERROR [tato.core.plugins.renamer] Failed renaming the file "Aeon Flux 2005 1080p BluRay DTS x264.mkv" : Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume2/movies/\xc3\x86on Flux (2005) [HD]/\xc3\x86on Flux.mkv' 
```

**Comment by avluis** [comment]
Reading over some of the open issues, I realize that this may be a duplicate, e.g; https://github.com/RuudBurger/CouchPotatoServer/issues/4449

Please close if necessary.
