### ISSUE TITLE
"Loading 'Snatched & Available'" request hanging for ever

### ISSUE THREAD

**Issue by cpoissonnier** [RuudBurger/CouchPotatoServer#4582]
### Steps to reproduce:
1. Login
2. Go to home page, and wait for ever

### Information:
Version of CouchPotato: desktop: 2.6.1
Running on: Windows, with directory/movie names with french characters (such as "à" or "é") pretty much everywhere

### Logs:
```
01-25 19:42:10 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "C:\Users\Clement\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\couchpotato\api.py", line 144, in taskFinished
  File "C:\Users\Clement\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\libs\tornado\web.py", line 655, in write
  File "C:\Users\Clement\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\libs\tornado\escape.py", line 88, in json_encode
  File "json\__init__.pyc", line 243, in dumps
  File "json\encoder.pyc", line 207, in encode
  File "json\encoder.pyc", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 86: invalid start byte 
```

Thanks !

**Comment by RuudBurger** [comment]
Disable torrentbytes. This is fixed in develop

**Comment by cpoissonnier** [comment]
Great, thanks for your reactivity !
