### ISSUE TITLE
Couch Potato unable to download NZB files

### ISSUE THREAD

**Issue by wipwar** [RuudBurger/CouchPotatoServer#4592]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: All Movies eg: Captain America The Winter Soilder
Quality of the movie being searched: "Best" 1080p or 720p or BD-RIP or DVD-Rip
Providers I use: Astrawebs
Version of CouchPotato: desktop: 2.6.1
Running on: Windows Server 2012

### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: desktop: 2.6.1
Running on: ...

### Logs:
```
01-28 21:34:28 ERROR [ase.providers.nzb.newznab] Failed download from api.nzb.su: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\couchpotato\core\media\_base\providers\nzb\newznab.py", line 186, in download
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\couchpotato\core\plugins\base.py", line 237, in urlopen
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\libs\requests\models.py", line 808, in raise_for_status
HTTPError: 403 Client Error: Forbidden 
```
```
01-28 20:55:58 ERROR [tato.core.plugins.release] Tried to download, but the "nzb" provider gave an error: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\couchpotato\core\plugins\release\main.py", line 311, in download
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\couchpotato\core\media\_base\providers\nzb\newznab.py", line 186, in download
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.1.win32\couchpotato\core\plugins\base.py", line 209, in urlopen
Exception: Disabled calls to %s for 15 minutes because so many failed requests 
```

**Comment by RuudBurger** [comment]
What's the log before this? It needs to contain the actual newznab profider url

**Comment by wipwar** [comment]
Edited

**Comment by RuudBurger** [comment]
Already fixed in develop
