### ISSUE TITLE
Couchpotato not connecting to Deluge.

### ISSUE THREAD

**Issue by cr0wburn** [RuudBurger/CouchPotatoServer#4682]
This issue was reported, but closed.
But it still persists with the current master and developer branch of CouchPotato.

Settings of deluge in couchpotato are correct, my SickRage installation works fine with the same user/password/ip:port settings. 

Clicking "Test" gives this error message in the web interface: "Test Connection failed. Check logs for details", but there is no corresponding log entry.

Version
b19b0775c7ca540c42a2fe9ed7aa36a43767689d (2/20/2015, 9:16:12 PM)
Updater source, develop ID 5600

This is the error message in the developer branch, and the master branch gives the exact same message.
I changed the movie name to "some moviename", the error can be reproduced on both my computers.

Error message:
02-21 00:29:35ERROR[o.core.downloaders.deluge] Failed to add torrent magnet magnet:?xt=urn:btih:E306EAE157E4FB3301F14ADC631C59D01963CA2C&dn=some moviename&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce: _ssl.c:489: The handshake operation timed out Traceback (most recent call last):
  File "C:\CouchPotatoServer\CouchPotatoServer-develop\couchpotato\core\downloaders\deluge.py", line 234, in add_torrent_magnet
    self.connect()
  File "C:\CouchPotatoServer\CouchPotatoServer-develop\couchpotato\core\downloaders\deluge.py", line 222, in connect
    self.client.connect(self.host, int(self.port), self.username, self.password)
  File "C:\CouchPotatoServer\CouchPotatoServer-develop\libs\synchronousdeluge\client.py", line 143, in connect
    self.transfer.connect((host, port))
  File "C:\CouchPotatoServer\CouchPotatoServer-develop\libs\synchronousdeluge\transfer.py", line 22, in connect
    self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE, ssl.PROTOCOL_TLSv1)
  File "C:\Python27\lib\ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 143, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: _ssl.c:489: The handshake operation timed out
02-21 00:29:35ERROR[o.core.downloaders.deluge] Failed sending torrent to Deluge

**Comment by dlage** [comment]
I guess this is a confirmed bug even on develop branch.
This happens on Debian trying to connect to deluge daemon on the same machine and I get no entries in any of the log files (both from CP and Deluge).
Can you tell me any way to try to get more logging so that it might help you with this issue?

Best regards

**Comment by stgarf** [comment]
Version abfd9d08 (3/23/2015, 8:23:09 AM)

Same deal:
```
03-25 00:07:56ERROR[o.core.downloaders.deluge] Failed to add torrent magnet magnet:?xt=urn:btih:16F5A846191676A0FC2C52621601CC5E48A64F0E&dn=some+movie&tr=udp%3A%2F%2F10.rarbg.me%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337: _ssl.c:489: The handshake operation timed out Traceback (most recent call last):
  File "/opt/CouchPotatoServer/couchpotato/core/downloaders/deluge.py", line 234, in add_torrent_magnet
    self.connect()
  File "/opt/CouchPotatoServer/couchpotato/core/downloaders/deluge.py", line 222, in connect
    self.client.connect(self.host, int(self.port), self.username, self.password)
  File "/opt/CouchPotatoServer/libs/synchronousdeluge/client.py", line 143, in connect
    self.transfer.connect((host, port))
  File "/opt/CouchPotatoServer/libs/synchronousdeluge/transfer.py", line 22, in connect
    self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE, ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: _ssl.c:489: The handshake operation timed out
03-25 00:07:56ERROR[o.core.downloaders.deluge] Failed sending torrent to Deluge
```

**Comment by Anthirian** [comment]
I'm having the same issue. See (part of) the bug report below.

### Information:
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) abfd9d08 (2015-03-23 15:23:09)
Running on: Raspberry Pi 2 with Raspbian

I don't use HTTPS for my host URL for Deluge, so I wonder why it still reports an SSL error.

### Logs:
```
03-26 10:56:02 ERROR [o.core.downloaders.deluge] Failed to add torrent magnet magnet:?xt=urn:btih:22E9145283B3DC479209CC0439E6A9DF6F412BDE&dn=hartenstraat+2014+1080p+nl+audio+bluray+sam+tbs&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce: [Errno 1] _ssl.c:504: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number Traceback (most recent call last):
  File "/opt/CouchPotato/couchpotato/core/downloaders/deluge.py", line 234, in add_torrent_magnet
    self.connect()
  File "/opt/CouchPotato/couchpotato/core/downloaders/deluge.py", line 222, in connect
    self.client.connect(self.host, int(self.port), self.username, self.password)
  File "/opt/CouchPotato/libs/synchronousdeluge/client.py", line 143, in connect
    self.transfer.connect((host, port))
  File "/opt/CouchPotato/libs/synchronousdeluge/transfer.py", line 22, in connect
    self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE, ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number 
```

**Comment by Z903** [comment]
Reverting commit 43af80a1375322626b13c040f060b6be288c0e02 seems to fix this. I have not thoroughly tested this.

**Comment by davebond** [comment]
Just run into this, workaround is:

1. Enable remote access to deluge daemon
2. Use the username and password in <deluged config dir>/auth

Auth file is in the format username:password:permissions

**Comment by Anthirian** [comment]
I already had remote access enabled from the get-go, and for me the workaround didn't work. The main reason for it is because I was running Deluge 1.3.3 on my Raspberry Pi 2. There was no updated version available through ``apt-get`` which lead me to believe I was running the latest version. I had to [install from source](http://dev.deluge-torrent.org/wiki/Installing/Source) in order to update. Judging from the commit referenced above CouchPotato currently only supports version 1.3.10 and above. I'm currently on 1.3.11 and both the connection test and the snatching test are successful.

**Comment by jensbodal** [comment]
So I don't have much control over my environment with regards to manually updating software, but I went ahead and manually changed the file referenced in the commit from @Z903 and restarted couchpotato and was immediately able to connect to deluge.  

My deluge is currently at 1.3.10 and CP at c295b344

**Comment by arjhun** [comment]
I can confirm that @Z903 worked for me...

also using deluge 1.3.10

**Comment by kars85** [comment]
Running a headless Ubuntu Server 14.04 - Deluge 1.3.11 and latest master build (7 days ago).

Setup an alternative auth file entry (username:password:10) in /var/lib/deluge/.config/deluge/auth, verified that it can connect to the daemon (port 58846) OK via my Deluge Mac client.

That being said, any number of combinations to test the connection within CP still fail, with not even a single debug log file entry generated.

Just a heads up that neither alternative workarounds worked for me.

**Comment by sharkoz** [comment]
Same problem here, test connection failed, nothing in the logs.

**Comment by misacek007** [comment]
I have checked out latest develop (c851786) and it is possible to add torrent to deluge as expected.

**Comment by githubbar** [comment]
No connecting as of  de141aa. Please fix!

**Comment by arbrick** [comment]
I had the same issue, updating to the latest version of deluge (1.3.12) fixed it for me.
NOTE: The update was done through an apt-get dist-upgrade, so I also had lots of other lib changes.

**Comment by brysbra** [comment]
Any news on this?
I have tried the workarounds described in the comments above but I'm still not able to use Deluge with Couchpotato. I'm running Deluge 1.3.12 and I'm on the develop branch.

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer develop) 90cbff2f (2016-02-11 08:00:13)
Running on: ...

### Logs:
```
02-12 00:21:31 ERROR [o.core.downloaders.deluge] Failed to add torrent magnet magnet:?xt=urn:btih:88c81886686da4dab1eb5bc1c778fdf5a9170b71&dn=Casper.1995.720p.BluRay.X264-AMIABLE&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969: _ssl.c:495: The handshake operation timed out Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/downloaders/deluge.py", line 237, in add_torrent_magnet
    self.connect()
  File "/opt/couchpotato/couchpotato/core/downloaders/deluge.py", line 225, in connect
    self.client.connect(self.host, int(self.port), self.username, self.password)
  File "/opt/couchpotato/libs/synchronousdeluge/client.py", line 143, in connect
    self.transfer.connect((host, port))
  File "/opt/couchpotato/libs/synchronousdeluge/transfer.py", line 22, in connect
    self.conn = ssl.wrap_socket(self.sock, None, None, False, ssl.CERT_NONE, ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: _ssl.c:495: The handshake operation timed out
 
```

**Comment by evalerr** [comment]
This worked for me :)

`GTK UI

The Deluge GTK UI setup require switching the GTK UI from Classic mode to Thin-client mode, then adding and connecting to the remote daemon on the server.

    In Preferences -> Interface and disable (untick) Classic Mode
    Restart deluge and you should see the Connection Manager.
        If it is not needed you can remove the localhost daemon.
        If SSH Tunnelling, before continuing Create SSH Tunnel, and for Hostname, below, 127.0.0.2 must be used. 
    Create a new entry with Add button:
        Hostname is your server's IP.
        Port should be default 58846.
        Username and Password are those added to the deluged config auth file. 

If this was successful a green tick should now appear as the status for the daemon you just added.

Click on Connect and the Connection Manager should disappear.

Optional step: Expand Options and select 'Automatically connect to selected host on startup' and 'Do not show this dialog on start-up'.

Congratulations! You can now access the Deluge daemon, deluged, on the server via the GTK UI. `

**Comment by maxbbender** [comment]
workaround that evaleer posted worked for me. Still weird that we have to expose the Daeomon to anything other than the local though.
