### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by Lbatson** [RuudBurger/CouchPotatoServer#4684]
### Steps to reproduce:
1. Refresh a movie and do a forced search

### Information:
Movie(s) I have this with: All
Quality of the movie being searched: 1080p
Providers I use: YIFY
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 55288ad6 (2015-02-18 10:21:39)
Running on: Synology Diskstation v5.0

### Logs:
```
02-20 18:33:29 ERROR [   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/torrent/yify.py", line 31, in search
    return super(Base, self).search(movie, quality)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 209, in search
    self._search(media, quality, results)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/torrent/yify.py", line 42, in _search
    data = data.get('data')
AttributeError: 'list' object has no attribute 'get'
encoding=UTF-8 debug=False args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf'] app_dir=/usr/local/couchpotatoserver/share/CouchPotatoServer data_dir=/usr/local/couchpotatoserver/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False) 
```

**Comment by RuudBurger** [comment]
Fixed in develop. Be sure see what the error before this is though.
