### ISSUE TITLE
Couchpotato not working since last update (02-15)

### ISSUE THREAD

**Issue by FuNK3Y** [RuudBurger/CouchPotatoServer#4686]
Hello,

The last update from yesterday broke my couchpotato:

Here is the last thing I get in the log:
02-15 16:55:56 INFO ^[[0m[potato.core._base.updater] Checking for new version on github for CouchPotatoServer^[[0m
02-15 16:55:56 ERROR ^[[31m[tato.core.plugins.renamer] Missing `cd` or `cd_nr` in the renamer. This will cause multi-file releases of being renamed to the same file. Please add it in the renamer settings. Force adding it for now.^[[0m
02-15 16:55:59 INFO ^[[0m[potato.core._base.updater] Updating to latest version^[[0m
02-15 16:56:04 INFO ^[[0m[core.notifications.email_] Email notification sent^[[0m
02-15 16:56:04 INFO ^[[0m[chpotato.core._base._core] Restarting^[[0m
02-15 16:56:04 INFO ^[[0mShutting down thread pool^[[0m

Here is what I have in the error log:
Traceback (most recent call last):
  File "CouchPotato.py", line 133, in <module>
    l.run()
  File "CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
    db.open()
  File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
    res = super(SuperThreadSafeDatabase, self).open(*args, **kwargs)
  File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
    index.open_index()
  File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 162, in open_index
    self._open_storage()
  File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 1923, in _open_storage
    self.storage.open()
  File "/opt/couchpotato/libs/CodernityDB/storage.py", line 99, in open
    raise IOError("Storage doesn't exists!")
IOError: Storage doesn't exists!

I did redownload from git minutes ago and it is still not working

**Comment by FuNK3Y** [comment]
I did nuke the DB, and I got it working again, but something went wrong during the update process

**Comment by RuudBurger** [comment]
Check the database backups. Should be in the data folder
