### ISSUE TITLE
CP post processing error

### ISSUE THREAD

**Issue by mochiware** [RuudBurger/CouchPotatoServer#4687]
Guys, I'm not sure what I'm doing wrong on CP as post processing isn't working at all for me. I'm running CP custom on a Synology. As an example below I have "300.Rise.of.an.Empire.2014.720p.BluRay.x264.YIFY.mp4" in my downloads folder "/volume1/Torrents/" and have set that in the "From" in CP with Folder Naming blank and File Naming <thename><cd>(<year>).<ext> and To /volume1/Movies/

I'm probably missing something obvious so please forgive my ignorance. Any help appreciated. 

### Logs:
```
02-22 07:36:45  INFO [hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/tt1253863?api_key=xxx&append_to_response=alternative_titles, data: [] 
02-22 07:36:45  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?i=tt1253863, data: [] 
02-22 07:36:45  INFO [ie.providers.info.omdbapi] Found: 300: Rise of an Empire (2014) 
02-22 07:36:46 ERROR [ato.core.plugins.subtitle] Failed searching for subtitle: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/subtitle.py", line 35, in searchSingle
    download = subliminal.download_subtitles(files, multi = True, force = self.conf('force'), languages = [lang], services = self.services, cache_dir = Env.get('cache_dir'))
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/subliminal/api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/subliminal/core.py", line 61, in create_list_tasks
    services = filter_services(services)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/subliminal/core.py", line 270, in filter_services
    mod = __import__('services.' + service_name, globals=globals(), locals=locals(), fromlist=['Service'], level=-1)
ImportError: No module named podnapisi 
02-22 07:36:46  INFO [tato.core.plugins.renamer] Moving "/volume1/Torrents/300.Rise.of.an.Empire.2014.720p.BluRay.x264.YIFY.mp4" to "/volume1/Movies/300 Rise of an Empire(2014).mp4" 
02-22 07:36:46 ERROR [tato.core.plugins.renamer] Couldn't move file "/volume1/Torrents/300.Rise.of.an.Empire.2014.720p.BluRay.x264.YIFY.mp4" to "/volume1/Movies/300 Rise of an Empire(2014).mp4": Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/volume1/Movies/300 Rise of an Empire(2014).mp4' 
02-22 07:36:46 ERROR [tato.core.plugins.renamer] Failed renaming the file "300.Rise.of.an.Empire.2014.720p.BluRay.x264.YIFY.mp4" : Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/volume1/Movies/300 Rise of an Empire(2014).mp4'

**Comment by RuudBurger** [comment]
`Permission denied`. can't help you out, you need to make sure this is set outside of CP properly
