### ISSUE TITLE
Error with renamer on win32

### ISSUE THREAD

**Issue by sunmorgus** [RuudBurger/CouchPotatoServer#4690]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: desktop: 2.6.2
Running on: ...

### Logs:
```
02-22 09:35:47 ERROR [tato.core.plugins.renamer] Failed checking snatched: Traceback (most recent call last):
  File "C:\Users\demayos\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.2.win32\couchpotato\core\plugins\renamer.py", line 925, in checkSnatched
  File "C:\Users\demayos\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.2.win32\couchpotato\core\plugins\release\main.py", line 539, in withStatus
  File "C:\Users\demayos\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.2.win32\libs\CodernityDB\database_super_thread_safe.py", line 43, in _inner
  File "C:\Users\demayos\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.2.win32\libs\CodernityDB\database.py", line 949, in get
  File "C:\Users\demayos\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.2.win32\libs\CodernityDB\storage.py", line 139, in get
  File "C:\Users\demayos\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-2.6.2.win32\libs\CodernityDB\storage.py", line 114, in data_from
EOFError: EOF read where object expected 
```

**Comment by sunmorgus** [comment]
Additional Info: I cleared all the directory settings in CP, and resaved them, to no avail. Also removed all the undetected movies from sab's completed directory and redownloaded just one movie, but still getting the error. Outside of uninstall/reinstall (which I would like to avoid), is there anything else I can try?
