### ISSUE TITLE
German Encoding 

### ISSUE THREAD

**Issue by gdomod** [RuudBurger/CouchPotatoServer#4794]
How can i set german locale ?

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) abfd9d08 (2015-03-23 16:23:09)
Running on: ...

### Logs:
```
03-28 19:07:41 ERROR [tato.core.plugins.renamer] Couldn't move file "/raid/downloads/couchpotato/tt2131628/tt2131628.mkv" to "/raid/share/moviez/2014/SchoÄÂgebete (2014)/SchoÄÂgebete.mkv": Traceback (most recent call last):
  File "/etc/couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/raid/share/moviez/2014/Scho\xc3\x9fgebete (2014)/Scho\xc3\x9fgebete.mkv' 
```

**Comment by RuudBurger** [comment]
This should already work. But make sure the system and filesystem is setup properly to support utf8
