### ISSUE TITLE
Error "elementTree.py"  when adding a specific film

### ISSUE THREAD

**Issue by starsys** [RuudBurger/CouchPotatoServer#4805]
### Steps to reproduce:
1. Add "Astérix : le domaine des dieux" movie as "wanted"
2. Check the logs

### Information:
Movie(s) I have this with: "Astérix : le domaine des dieux"
Quality of the movie being searched: HD
Providers I use: Dognzb, cpasbien, binnews, nzb.su
Version of CouchPotato: git:(sarakha63:CouchPotatoServer master) 6e7544e5 (2015-03-22 19:22:42)
Running on: Synology NAS DS411 II+

### Logs:
```
03-31 09:30:15 ERROR [edia._base.providers.base] Failed to parsing Newznab: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 95, in getRSSData
    data = XMLTree.fromstring(ss(data))
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0 
```

**Comment by RuudBurger** [comment]
Invalid xml returend from the newznab provider.
