### ISSUE TITLE
.srt files not moved with movie files

### ISSUE THREAD

**Issue by mnbf9rca** [RuudBurger/CouchPotatoServer#5120]
### Steps to reproduce:
1. download this release...
2. processing set to move files to a share mounted locally.

### Information:
Movie(s) I have this with: so far, everything that includes .srt files in the source
Quality of the movie being searched: ...
Providers I use: cheapnews, tweaknews
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 13:06:41)
Running on: ubuntu 14.04 LTS

### Logs:
```
07-09 09:49:30  INFO [ie.providers.info.omdbapi] Found: NausicaĂ¤ of the Valley of the Wind (1984) 
07-09 09:49:30  INFO [tato.core.plugins.renamer] Removing "/home/robert/Downloads/nzb/complete/movies-unprocessed/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.cp(tt0087544)/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.nfo" 
07-09 09:49:30  INFO [tato.core.plugins.renamer] Removing "/home/robert/Downloads/nzb/complete/movies-unprocessed/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.cp(tt0087544)/Kaze.no.tani.no.Naushika.1984.720p.BluRay.x264-CtrlHD.nfo" 
07-09 09:49:30  INFO [tato.core.plugins.renamer] Moving "/home/robert/Downloads/nzb/complete/movies-unprocessed/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.cp(tt0087544)/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.spanish.srt" to "/mnt/video/movies/N/NausicaÄÂ¤ of the Valley of the Wind.srt" 
07-09 09:49:30 ERROR [tato.core.plugins.renamer] Couldn't move file "/home/robert/Downloads/nzb/complete/movies-unprocessed/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.cp(tt0087544)/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.spanish.srt" to "/mnt/video/movies/N/NausicaĂÂĂÂ¤ of the Valley of the Wind.srt": Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/mnt/video/movies/N/Nausica\xc4\x82\xc2\xa4 of the Valley of the Wind.srt' 
07-09 09:49:30 ERROR [tato.core.plugins.renamer] Failed renaming the file "Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.spanish.srt" : Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/opt/couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/mnt/video/movies/N/Nausica\xc4\x82\xc2\xa4 of the Valley of the Wind.srt' 
```

**Comment by mnbf9rca** [comment]
my fault - is an issue with permissions on my machine
