### ISSUE TITLE
Renamer Failing on a "-"

### ISSUE THREAD

**Issue by tedrock** [RuudBurger/CouchPotatoServer#5206]
CouchPotato version 69825f9dbdfc42d5e6fcebd89828e21ff36330fa (5/27/2015, 1:06:41 PM)
Updatersource, masterID5525
Running in a FreeNAS [9.2.1.5-RELEASE-x64 (80c1d35)] jail

I recently aquired "Mission: Impossible - Ghost Protocol" and when the renamer hits it I get the following error:
```
08-09 11:47:42DEBUG[tato.core.plugins.scanner] Found 1 files to scan and group in /media/Downloads/Complete/Movies
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Getting cache ['/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol']
08-09 11:47:42DEBUG[tato.core.plugins.scanner] Grouping files: mission impossible 4
08-09 11:47:42DEBUG[tato.core.plugins.scanner] Getting metadata for mission impossible 4
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Getting cache ['/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol']
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 1080p via tags ['m2ts', 'x264', 'h264', '1080'] in /media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 1080p with .mkv extension in /media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 720p via identifier 720p in /media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 720p via tags ['x264', 'h264', '720'] in /media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 720p with .mkv extension in /media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 1080p via release size: 2800.0 MB < 4900.0 MB < 40000.0 MB
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 720p via release size: 1400.0 MB < 4900.0 MB < 40000.0 MB
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found 720p via resolution_width: 1280 == 1280
08-09 11:47:42DEBUG[tato.core.plugins.quality] Found brrip via release size: 1400.0 MB < 4900.0 MB < 40000.0 MB
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Setting cache ['/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol']
08-09 11:47:42DEBUG[tato.core.plugins.scanner] Found movie via imdb in filename: None
08-09 11:47:42INFO[tato.core.plugins.scanner] Found 1 movies in the folder /media/Downloads/Complete/Movies
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Acquiring lock: media.get.eb8d5fdfbbaa4639b5a4f171e89de046
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Getting cache e655a1e9c2f11220860813028ba9f5c6
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Getting cache d97f2d599bc7e0792b4dd111b7af7928
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Getting cache omdbapi.cache.tt1229238
08-09 11:47:42INFO[ie.providers.info.omdbapi] Found: Mission: Impossible - Ghost Protocol (2011)
08-09 11:47:42DEBUG[   couchpotato.core.event] Return modified results for movie.info
08-09 11:47:42DEBUG[to.core.media.movie._base] Adding titles: [u'Mission: Impossible \u2013 Ghost Protocol', u'M:i-4 - Mission: Impossible 4', u'Miss\xe3o Imposs\xedvel: Opera\xe7\xe3o Fantasma', u'Misi\xf3n imposible 4', u'Mission Impossible IV', u'Mission Impossible 4', u'Mission Impossible IV - Ghost Protocol', u'Mission Impossible 4 - Ghost Protocol', u'Mission Impossible Ghost Protocol', u'Mission Impossible - Ghost Protocol', u'Misi\xf3n Imposible 4', u'Mission Impossible - Aries', u'Mission: Impossible IV - Ghost Protocol', u'\u4e0d\u53ef\u80fd\u7684\u4efb\u52d9\uff1a\u9b3c\u5f71\u884c\u52d5', u'\u041c\u0438\u0441\u0441\u0438\u044f: \u041d\u0435\u0432\u044b\u043f\u043e\u043b\u043d\u0438\u043c\u0430 4', u'Mission Impossible - Phantom Protokoll', u'Mission: Impossible - Phantom Protokoll', u'Mission - Impossible - Ghost Protocol', u'Mission- Impossible - Ghost Protocol', u'Mission - Impossible 4', u'Mission- Impossible 4', u'Mission Impossible protocole fant\xf4me', u'Misi\xf3n imposible: Protocolo fantasma', u'Mission Impossible - IM4 - Ghost Protocol', u'Mission impossible : Protocole Fant\xf4meMission impossible : Protocole Fant\xf4me', u'Mission: Impossible - Ghost Protocol']
08-09 11:47:42DEBUG[hpotato.core.plugins.base] Releasing lock: media.get.eb8d5fdfbbaa4639b5a4f171e89de046
08-09 11:47:42DEBUG[ato.core.plugins.subtitle] Searching for subtitles for: [u'/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv']
08-09 11:47:43ERROR[31mError consuming task ListTask(Movie(/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv), language_set([Language(English)]), subscenter, ServiceConfig(True, /usr/pbi/couchpotato-amd64/etc/couchpotato/cache))
UNKNOWNUNKNOWN[tato.core.plugins.renamer] Skipping, renaming of nfo disabled
08-09 11:47:43DEBUG[tato.core.plugins.renamer] Removing leftover files
08-09 11:47:43INFO[tato.core.plugins.renamer] Moving "/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv" to "/media/Movies/Mission Impossible Ă˘ÂÂ Ghost Protocol [2011]/Mission Impossible Ă˘ÂÂ Ghost Protocol [2011].mkv"
08-09 11:47:43ERROR[tato.core.plugins.renamer] Couldn't move file "/media/Downloads/Complete/Movies/Mission Impossible 4 720p x264 cp(tt1229238)/Mission Impossible - Ghost Protocol.mkv" to "/media/Movies/Mission Impossible Ă˘ÂÂ Ghost Protocol [2011]/Mission Impossible Ă˘ÂÂ Ghost Protocol [2011].mkv": Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/Movies/Mission Impossible \xe2\x80\x93 Ghost Protocol [2011]/Mission Impossible \xe2\x80\x93 Ghost Protocol [2011].mkv'
08-09 11:47:43ERROR[tato.core.plugins.renamer] Failed renaming the file "Mission Impossible - Ghost Protocol.mkv" : Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/Movies/Mission Impossible \xe2\x80\x93 Ghost Protocol [2011]/Mission Impossible \xe2\x80\x93 Ghost Protocol [2011].mkv'
```

You will notice it makes a "Mission Impossible A?Â?Â? Ghost Protocol" folder rather a "Mission Impossible - Ghost Protocol" folder. (In Windows it's viewed as "Mission Impossible â Ghost Protocol [2011]"

It handled all other Mission: Impossible titles without issue. The title on the IMDb is "Mission: Impossible - Ghost Protocol".

**Comment by tedrock** [comment]
Same issue is occurring with "Mission: Impossible - Rogue Nation"

**Comment by RuudBurger** [comment]
Seems to be a unicode issue

**Comment by hasan37** [comment]
has this been fixed?

**Comment by luxferro** [comment]
I'm also having this issue.. would be nice if linked to a solution instead of just closing it...

**Comment by hpbrad** [comment]
same issue cant seem to find any fix for this and ive tried multiple methods of creating the nfo file but clearly thats not the problem.  definitely seems to be with creating the destination folder/files... any help would be greatly appreciated

**Comment by henryford** [comment]
@luxferro He didn't "just close the issue" - he tagged it with "Already reported" and "Unicode". If you look at the problems under the tag "Unicode" you'd notice there are issues quite similiar to the current one. So, he's aware of the issue and is trying to fix it - but there is no sense in keeping open multiple issues for the same thing.

**Comment by hpbrad** [comment]
@henryford that workaround doesn't solve the issue of downloading the metadata subs and trailer that couchpotato normally does. Is there a simple workaround for that?

**Comment by henryford** [comment]
@hpbrad: You're right, didn't think of that. I'm not exactly sure here - does cp load the metadata, subs and trailer first to a temporary location and moves it afterwards? If so, you could find those temporary files and move them by yourself. I hate that we're in 2015 and yet have to figure out this encoding stuff...

However, what needs to happen is a cleanup of all those pesky characters - found something which might be of use here:
http://blog.luminoso.com/2012/08/20/fix-unicode-mistakes-with-python/

Could someone more competent than me take a look at it?
