### ISSUE TITLE
Bug  dans le fichier de log

### ISSUE THREAD

**Issue by kesurof** [RuudBurger/CouchPotatoServer#5389]
### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(sarakha63:CouchPotatoServer master) 471c77b2 (2015-09-06 01:22:27)
Running on: ...

### Logs:
```
09-06 22:11:02 ERROR [   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/var/www/couchpotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/var/www/couchpotato/couchpotato/core/media/_base/providers/base.py", line 214, in search
    self._search(media, quality, results)
  File "/var/www/couchpotato/couchpotato/core/media/_base/providers/torrent/t411.py", line 94, in _search
    r = self.opener.open(URL)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
encoding=UTF-8 debug=False args=['--quiet', '--daemon', '--pid_file=/var/run/couchpotato/couchpotato.pid', '--data_dir=/var/opt/couchpotato'] app_dir=/var/www/couchpotato data_dir=/var/opt/couchpotato desktop=None options=Namespace(config_file='/var/opt/couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/var/opt/couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=True)  
```

**Comment by RuudBurger** [comment]
Not my repo
