### ISSUE TITLE
Renamer can't move to a created folder

### ISSUE THREAD

**Issue by ziedby** [RuudBurger/CouchPotatoServer#5508]
Hi,

Couchpotato seems to have an issue while moving a file to a created folder. The folder name seems to be wrongly encoded.

### Steps to reproduce:
1. Download movie with nzbGet
2. Waits the renamer to run auto

### Information:
Movie(s) I have this with: Mission: Impossible - Rogue Nation (2015)
Quality of the movie being searched: 1080
Providers I use: //
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 63560efe (2015-08-31 23:26:55)
Running on: Synology ds214play

### Logs:
```
09-25 23:04:17  INFO [tato.core.plugins.scanner] Found 1 movies in the folder /volume1/Downloads/Usenet/complete/Movies 
09-25 23:04:17  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2381249, data: [] 
09-25 23:04:17  INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt2381249?api_key=xxx&append_to_response=alternative_titles, data: [] 
09-25 23:04:17  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2381249/, data: [] 
09-25 23:04:17  INFO [ie.providers.info.omdbapi] Found: Mission: Impossible - Rogue Nation (2015) 
09-25 23:04:20  INFO [tato.core.plugins.renamer] Moving "/volume1/Downloads/Usenet/complete/Movies/Mission.Impossible.Rogue.Nation (2015).cp(tt2381249)/Mission.Impossible.Rogue.Nation (2015).mkv" to "/volume1/Movies/Mission Impossible â Rogue Nation (2015)/Mission Impossible â Rogue Nation (2015).mkv" 
09-25 23:04:21 ERROR [tato.core.plugins.renamer] Couldn't move file "/volume1/Downloads/Usenet/complete/Movies/Mission.Impossible.Rogue.Nation (2015).cp(tt2381249)/Mission.Impossible.Rogue.Nation (2015).mkv" to "/volume1/Movies/Mission Impossible Ă˘ÂÂ Rogue Nation (2015)/Mission Impossible Ă˘ÂÂ Rogue Nation (2015).mkv": Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/Movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation (2015).mkv'
 
09-25 23:04:21 ERROR [tato.core.plugins.renamer] Failed renaming the file "Mission.Impossible.Rogue.Nation (2015).mkv" : Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/Movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation (2015).mkv'
 
```

Thank you

**Comment by sparklyballs** [comment]
also seeing exact same issue with same movie

**Comment by RuudBurger** [comment]
Known and reported issue, thanks
