### ISSUE TITLE
Rename "Mission Impossible 5 - Rogue Nation" on Windows OS fails because of character

### ISSUE THREAD

**Issue by Rouzax** [RuudBurger/CouchPotatoServer#5648]
### Steps to reproduce:
1. Rename Mission Impossible 5 - Rogue Nation on Windows OS
2. Gives invalid file path

### Information:
Movie(s) I have this with: Mission Impossible 5 - Rogue Nation
Providers I use: IPtortrent
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 11:13:08)
Running on: Windows Server 2012 R2

### Logs:
```
10-31 17:22:50 INFO [tato.core.plugins.scanner] Found 1 movies in the folder C:\_Data\Private\uTorrent\_Proccessed\Movies 
10-31 17:22:50 DEBUG [hpotato.core.plugins.base] Acquiring lock: media.get.5dd1e984062e408b89386ef49be24c48 
10-31 17:22:50 DEBUG [hpotato.core.plugins.base] Getting cache 7c9ce985e493083386c912567ef07445 
10-31 17:22:50 DEBUG [hpotato.core.plugins.base] Getting cache omdbapi.cache.tt2381249 
10-31 17:22:50 DEBUG [hpotato.core.plugins.base] Getting cache 0a7624e37b02c3576bce8c75e86bdb17 
10-31 17:22:50 INFO [ie.providers.info.omdbapi] Found: Mission: Impossible - Rogue Nation (2015) 
10-31 17:22:50 DEBUG [   couchpotato.core.event] Return modified results for movie.info 
10-31 17:22:50 DEBUG [to.core.media.movie._base] Adding titles: [u'Mission: Impossible \u2013 Rogue Nation', u'M:i 5', u'\u041c\u0438\u0441\u0441\u0438\u044f \u043d\u0435\u0432\u044b\u043f\u043e\u043b\u043d\u0438\u043c\u0430: \u041f\u043b\u0435\u043c\u044f \u0438\u0437\u0433\u043e\u0435\u0432', u'\u4e0d\u53ef\u80fd\u7684\u4efb\u52d9\uff1a\u5931\u63a7\u570b\u5ea6', u'Miss\xe3o: Imposs\xedvel - Na\xe7\xe3o Secreta', u'M.I. 5 - Naci\xf3n Secreta', u'Mision Imposible 5 Nacion Secreta', u'Mission Impossible: Rogue Nation', u'Mission Impossible 5 - Rogue Nation', u'Miss\xe3o Imposs\xedvel 5 - Na\xe7\xe3o Secreta', u'\u0395\u03c0\u03b9\u03ba\u03af\u03bd\u03b4\u03c5\u03bd\u03b7 \u0391\u03c0\u03bf\u03c3\u03c4\u03bf\u03bb\u03ae: \u039c\u03c5\u03c3\u03c4\u03b9\u03ba\u03cc \u0388\u03b8\u03bd\u03bf\u03c2', u'Mission: Impossible - Rogue Nation'] 
10-31 17:22:50 DEBUG [hpotato.core.plugins.base] Releasing lock: media.get.5dd1e984062e408b89386ef49be24c48 
10-31 17:22:50 DEBUG [ato.core.plugins.subtitle] Searching for subtitles for: [u'C:\\_Data\\Private\\uTorrent\\_Proccessed\\Movies\\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS\\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv'] 
10-31 17:22:50 ERROR [31mError consuming task ListTask(Movie(C:\_Data\Private\uTorrent\_Proccessed\Movies\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv), language_set([Language(English)]), subscenter, ServiceConfig(True, C:\CouchConfig\cache)) 
UNKNOWN UNKNOWN [tato.core.plugins.renamer] Skipping, renaming of nfo disabled 
10-31 17:22:51 DEBUG [tato.core.plugins.renamer] Removing leftover files 
10-31 17:22:51 DEBUG [ato.core.helpers.encoding] Failed ss encoding char, force UTF8: 'charmap' codec can't encode character u'\x96' in position 35: character maps to <undefined> 
10-31 17:22:51 ERROR [hpotato.core.plugins.base] Unable to create folder "C:\_Data\Movies\Mission Impossible ? Rogue Nation (2015)": [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\_Data\\Movies\\Mission Impossible ? Rogue Nation (2015)' 
10-31 17:22:51 INFO [tato.core.plugins.renamer] Moving "C:\_Data\Private\uTorrent\_Proccessed\Movies\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv" to "C:\_Data\Movies\Mission Impossible – Rogue Nation (2015)\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv" 
10-31 17:22:51 ERROR [tato.core.plugins.renamer] Couldn't move file "C:\_Data\Private\uTorrent\_Proccessed\Movies\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv" to "C:\_Data\Movies\Mission Impossible – Rogue Nation (2015)\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv": Traceback (most recent call last):
  File "C:\GitHub\CouchPotatoServer\couchpotato\core\plugins\renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "C:\Python27\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\_Data\\Movies\\Mission Impossible \x96 Rogue Nation (2015)\\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv'
 
10-31 17:22:51 ERROR [tato.core.plugins.renamer] Failed renaming the file "Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv" : Traceback (most recent call last):
  File "C:\GitHub\CouchPotatoServer\couchpotato\core\plugins\renamer.py", line 620, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "C:\GitHub\CouchPotatoServer\couchpotato\core\plugins\renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "C:\Python27\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\_Data\\Movies\\Mission Impossible \x96 Rogue Nation (2015)\\Mission.Impossible.Rogue.Nation.2015.720p.BluRay.x264-SPARKS.mkv'
 
```

**Comment by lepis0** [comment]
I have the same problem aswell. With Synology NAS.

**Comment by Rouzax** [comment]
When changing the movie name in Couchpotato it will process correctly.
![image](https://cloud.githubusercontent.com/assets/4103090/10876844/d17e1a9c-8140-11e5-8685-2e6254ce0ba5.png)

**Comment by jknight2014** [comment]
This happens on Ubuntu too. CP Creates folder with the characters but tries to find it again with the hex equivalents. Changing the release options does not help.

**Comment by runderekrun** [comment]
@jknight2014 

Worked for me on Ubuntu. Be sure to select "Mission Impossible 5 - Rogue Nation".
