### ISSUE TITLE
Couchpotato attempts to create a folder with a question mark in it

### ISSUE THREAD

**Issue by JimboSliceX81** [RuudBurger/CouchPotatoServer#5650]
10-31 18:08:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/search/Mission+Impossible+Rogue+Nation+2015/?limit=1, data: [][0m
10-31 18:08:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=mission+impossible+rogue+nation&year=2015, data: [][0m
10-31 18:08:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&y=2015&t=mission+impossible+rogue+nation, data: [][0m
10-31 18:08:47 INFO [0m[ie.providers.info.omdbapi] Found: Mission: Impossible - Rogue Nation (2015)[0m
10-31 18:08:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/177677?api_key=xxx&append_to_response=alternative_titles, data: [][0m
10-31 18:08:47 INFO [0m[providers.info.themoviedb] Found: [u'Mission: Impossible \u2013 Rogue Nation (2015)'][0m
10-31 18:08:47 INFO [0m[tato.core.plugins.scanner] Found 1 movies in the folder C:\Junk\Downloads\complete\!movies[0m
10-31 18:08:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2381249/, data: [][0m
10-31 18:08:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2381249, data: [][0m
10-31 18:08:47 INFO [0m[ie.providers.info.omdbapi] Found: Mission: Impossible - Rogue Nation (2015)[0m
10-31 18:08:48 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt2381249?api_key=xxx&append_to_response=alternative_titles, data: [][0m
10-31 18:08:48 ERROR [31m[hpotato.core.plugins.base] Unable to create folder "Y:\Movies\Mission Impossible ? Rogue Nation (2015)": [Error 123] The filename, directory name, or volume label syntax is incorrect: 'Y:\\Movies\\Mission Impossible ? Rogue Nation (2015)'[0m
10-31 18:08:48 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.imdb.com/boxoffice/rentals, data: [][0m
10-31 18:08:48 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.blu-ray.com/rss/newreleasesfeed.xml, data: [][0m
10-31 18:08:48 INFO [0m[tato.core.plugins.renamer] Moving "C:\Junk\Downloads\complete\!movies\Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS\mission.impossible.rogue.nation.2015.1080p.bluray.x264-sparks.nfo" to "Y:\Movies\Mission Impossible – Rogue Nation (2015)\Mission Impossible – Rogue Nation.orig.nfo"[0m
10-31 18:08:48 ERROR [31m[tato.core.plugins.renamer] Couldn't move file "C:\Junk\Downloads\complete\!movies\Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS\mission.impossible.rogue.nation.2015.1080p.bluray.x264-sparks.nfo" to "Y:\Movies\Mission Impossible – Rogue Nation (2015)\Mission Impossible – Rogue Nation.orig.nfo": Traceback (most recent call last):
  File "C:\Users\jphillips\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\plugins\renamer.py", line 824, in moveFile
  File "shutil.pyc", line 302, in move
  File "shutil.pyc", line 130, in copy2
  File "shutil.pyc", line 83, in copyfile
IOError: [Errno 2] No such file or directory: 'Y:\\Movies\\Mission Impossible \x96 Rogue Nation (2015)\\Mission Impossible \x96 Rogue Nation.orig.nfo'
[0m
10-31 18:08:48 ERROR [31m[tato.core.plugins.renamer] Failed renaming the file "mission.impossible.rogue.nation.2015.1080p.bluray.x264-sparks.nfo" : Traceback (most recent call last):
  File "C:\Users\jphillips\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\plugins\renamer.py", line 620, in scan
  File "C:\Users\jphillips\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\plugins\renamer.py", line 824, in moveFile
  File "shutil.pyc", line 302, in move
  File "shutil.pyc", line 130, in copy2
  File "shutil.pyc", line 83, in copyfile
IOError: [Errno 2] No such file or directory: 'Y:\\Movies\\Mission Impossible \x96 Rogue Nation (2015)\\Mission Impossible \x96 Rogue Nation.orig.nfo'
[0m

**Comment by Rouzax** [comment]
When changing the movie name from Couchpotato it will process correctly.
![image](https://cloud.githubusercontent.com/assets/4103090/10876844/d17e1a9c-8140-11e5-8685-2e6254ce0ba5.png)
see https://github.com/RuudBurger/CouchPotatoServer/issues/5648

**Comment by JimboSliceX81** [comment]
I had no idea that feature existed, thanks!
