### ISSUE TITLE
error renaming

### ISSUE THREAD

**Issue by clarenceb5** [RuudBurger/CouchPotatoServer#5651]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: desktop: 3.0.1
Running on: ...

### Logs:
```
10-31 19:36:35  INFO [tato.core.plugins.renamer] Moving "Z:\Complete\Movies\Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.cp(tt2381249)\Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.sub" to "V:\Movies\Mission Impossible – Rogue Nation (2015)\Mission Impossible – Rogue Nation (2015) 1080p.sub" 
10-31 19:36:35 ERROR [tato.core.plugins.renamer] Couldn't move file "Z:\Complete\Movies\Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.cp(tt2381249)\Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.sub" to "V:\Movies\Mission Impossible – Rogue Nation (2015)\Mission Impossible – Rogue Nation (2015) 1080p.sub": Traceback (most recent call last):
  File "C:\Users\clayt\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\plugins\renamer.py", line 824, in moveFile
  File "shutil.pyc", line 302, in move
  File "shutil.pyc", line 130, in copy2
  File "shutil.pyc", line 83, in copyfile
IOError: [Errno 2] No such file or directory: 'V:\\Movies\\Mission Impossible \x96 Rogue Nation (2015)\\Mission Impossible \x96 Rogue Nation (2015) 1080p.sub'
 
10-31 19:36:35 ERROR [tato.core.plugins.renamer] Failed renaming the file "Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.sub" : Traceback (most recent call last):
  File "C:\Users\clayt\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\plugins\renamer.py", line 620, in scan
  File "C:\Users\clayt\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\plugins\renamer.py", line 824, in moveFile
  File "shutil.pyc", line 302, in move
  File "shutil.pyc", line 130, in copy2
  File "shutil.pyc", line 83, in copyfile
IOError: [Errno 2] No such file or directory: 'V:\\Movies\\Mission Impossible \x96 Rogue Nation (2015)\\Mission Impossible \x96 Rogue Nation (2015) 1080p.sub'
 
```

**Comment by Rouzax** [comment]
When changing the movie name from Couchpotato it will process correctly.
![image](https://cloud.githubusercontent.com/assets/4103090/10876844/d17e1a9c-8140-11e5-8685-2e6254ce0ba5.png)
see https://github.com/RuudBurger/CouchPotatoServer/issues/5648
