### ISSUE TITLE
renamer issue - being replaced with â

### ISSUE THREAD

**Issue by MikeBuzz** [RuudBurger/CouchPotatoServer#5671]
### Steps to reproduce:
renamer is replacing - with â

### Information:
Movie(s) I have this with: Mission.Impossible.Rogue.Nation.2015
Quality of the movie being searched: Any
Providers I use: 
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 10:13:08)
Running on: Ubuntu

### Logs:
```
11-05 10:56:14 ERROR [tato.core.plugins.renamer] Couldn't move file "/storage/downloads/complete/Movies/Mission.Impossible.Rogue.Nation.2015.MULTi.1080p.BluRay.x264-VENUE.cp(tt2381249)/Mission.Impossible.Rogue.Nation.2015.MULTi.1080p.BluRay.x264-VENUE.mkv" to "/storage/media/movies/Mission Impossible â Rogue Nation (2015)/Mission Impossible â Rogue Nation.mkv": Traceback (most recent call last):
  File "/storage/apps/couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/storage/media/movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation.mkv'
 
```

**Comment by pengc99** [comment]
Having the same issue. Thought it was the ":" causing the problem, but looks like it may be the "-"
