### ISSUE TITLE
renamer.py dies ungracefully upon special character in movie name

### ISSUE THREAD

**Issue by kolomanschaft** [RuudBurger/CouchPotatoServer#5674]
### Steps to reproduce:
1. Just tried to download a Movie (Mission Impossible - Rogue Nation)
2. After completion CP refuses to move/rename the movie

### Information:
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 10:13:08)
Running on: FreeNAS (FreeBSD 9.3) as plugin

Checked permissions, everything is fine. CP manages to create a destination folder. I'm very suspicious about the dash in the movie name though! They differ even in the error message:
`Mission Impossible â Rogue Nation` vs. `Mission Impossible \xe2\x80\x93 Rogue Nation`

### Logs:
```
11-06 14:02:44 ERROR [tato.core.plugins.renamer] Couldn't move file "/mnt/multimedia/usenet/complete/couchpotato/Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.cp(tt2381249)/Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.sub" to "/mnt/multimedia/movies/Mission Impossible â Rogue Nation (2015)/Mission Impossible â Rogue Nation.2015.1080p.H264.sub": Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/mnt/multimedia/movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation.2015.1080p.H264.sub'
 
```

**Comment by omgapuppy** [comment]
possible unicode issue?
