### ISSUE TITLE
Blank home screen - other screens work fine. Searched other issues but didn't seem relevant to my errors

### ISSUE THREAD

**Issue by reasonableone** [RuudBurger/CouchPotatoServer#5697]
### Steps to reproduce:
1. When starting, home screen is blank. I have automatic updates enabled so this may have occurred during an update.
2. Manage and movies screens work fine. Application is downloading movies in the wanted list.

### Information:
Movie(s) I have this with: Not related to a specific movie
Quality of the movie being searched: 720, dvdrip, but the trouble is the home screen
Providers I use: Usenetserver
Version of CouchPotato: desktop: 3.0.1
Running on: Windows 10

### Logs:
```
11-13 17:26:56 ERROR [tato.core.plugins.scanner] Couldn't find any movie files for the intern 2015 
11-13 17:27:03 ERROR [          couchpotato.api] Failed doing api request "media.list": Traceback (most recent call last):
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\api.py", line 36, in run_handler
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\media\main.py", line 321, in listView
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\media\main.py", line 260, in list
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\database.py", line 1000, in get_many
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\database_safe_shared.py", line 39, in next
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\tree_index.py", line 1594, in _find_key_many
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\rr_cache_with_lock.py", line 38, in wrapper
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\tree_index.py", line 193, in _read_leaf_nr_of_elements_and_neighbours
error: unpack requires a string argument of length 10
 
11-13 17:27:03 ERROR [chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1441070477', 'message': u"safari 9: \nTypeError: undefined is not an object (evaluating 'movies.length')", 'line': u'863', 'page': u'http://HOST/', '_request': <couchpotato.api.ApiHandler object at 0x08CBCA30>} 
11-13 17:27:21 ERROR [          couchpotato.api] Failed doing api request "media.list": Traceback (most recent call last):
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\api.py", line 36, in run_handler
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\media\main.py", line 321, in listView
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\media\main.py", line 260, in list
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\database.py", line 1000, in get_many
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\database_safe_shared.py", line 39, in next
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\tree_index.py", line 1594, in _find_key_many
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\rr_cache_with_lock.py", line 38, in wrapper
  File "C:\Users\temp\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\libs\CodernityDB\tree_index.py", line 193, in _read_leaf_nr_of_elements_and_neighbours
error: unpack requires a string argument of length 10
 
11-13 17:27:22 ERROR [chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1441070477', 'message': u"safari 9: \nTypeError: undefined is not an object (evaluating 'movies.length')", 'line': u'863', 'page': u'http://HOST/home/', '_request': <couchpotato.api.ApiHandler object at 0x051694D0>} 
```

**Comment by reasonableone** [comment]
Never mind. I deleted my installation and reinstalled. Works fine now
