### ISSUE TITLE
couchpotato.core.event errors keep CP from post processing downloads

### ISSUE THREAD

**Issue by iFloris** [RuudBurger/CouchPotatoServer#5702]
### Steps to reproduce:
1. download movie with CP
2. have CP see movie

### Information:
Movie(s) I have this with: all right now
Quality of the movie being searched: 720p
Providers I use: sunnyusenet
Version of CouchPotato: desktop: 3.0.1
Running on: osx 10.11.1

### Logs:
```
11-14 19:30:57 ERROR [tato.core.plugins.renamer] Missing `cd` or `cd_nr` in the renamer. This will cause multi-file releases of being renamed to the same file. Please add it in the renamer settings. Force adding it for now. 
11-14 19:30:57  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/example/, data: [] 
11-14 19:30:57  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i= example, data: [] 
11-14 19:30:57  INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/example?api_key=xxx&append_to_response=alternative_titles, data: [] 
11-14 19:30:59  INFO [ie.providers.info.omdbapi] Found: example (2010) 
11-14 19:31:00 ERROR [   couchpotato.core.event] Error in event "release.for_media", that wasn't caught: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/event.py", line 15, in runHandler
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/plugins/release/main.py", line 554, in forMedia
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/CodernityDB/database.py", line 942, in get
RecordNotFound: Location '09974b9a2eb543cc8816b872d3f3a8a6' not found
encoding=UTF-8 debug=False args=['--quiet'] app_dir=/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7 data_dir=/Users/administrator/Library/Application Support/CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x1004eec60> > options=Namespace(config_file='/Users/administrator/Library/Application Support/CouchPotato/settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='/Users/administrator/Library/Application Support/CouchPotato/couchpotato.pid', quiet=True)  
11-14 19:31:00 ERROR [.providers.info._modifier] Tried getting more info on searched movies: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/movie/providers/info/_modifier.py", line 117, in getLibraryTags
TypeError: 'NoneType' object is not iterable
 
```

**Comment by iFloris** [comment]
Well, this seems to have fixed itself. Not sure when CP started working again, noticed it when films started appearing in Plex. Closing this issue.
