### ISSUE TITLE
Errors with remote transmission

### ISSUE THREAD

**Issue by Wobak** [RuudBurger/CouchPotatoServer#5706]
### Steps to reproduce:
1. Use transmission on a different machine that uses its own file structure.
2. Add a movie

The file structure does not exist on the machine that uses couchpotato, but that should not matter.
I'm adding using a RPC URL with a download path for transmission. Then there is a mount point using NFS where I ask the post processing to copy the files from. So the path that is sent to transmission shouldn't be checked on the local filesystem.

### Information:
Movie(s) I have this with: Irrelevant
Quality of the movie being searched: Irrelevant
Providers I use: Irrelevant
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 11:13:08)
Running on: CentOS 7.1

### Logs:
```
11-16 14:31:32 ERROR [tato.core.plugins.browser] Failed getting directory "/opt/ftpusers/wobak/thib/CP" : Traceback (most recent call last):
  File "/opt/couchpotato/CouchPotatoServer/couchpotato/core/plugins/browser.py", line 88, in view
    dirs = self.getDirectories(path = path, show_hidden = show_hidden)
  File "/opt/couchpotato/CouchPotatoServer/couchpotato/core/plugins/browser.py", line 61, in getDirectories
    for f in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/opt/ftpusers/wobak/thib/CP'
 
```

**Comment by Wobak** [comment]
Of course the path exists on the machine that is running transmission (in case you're wondering)
