### ISSUE TITLE
Resolved most of my issues CP still unable to login to Scene Access

### ISSUE THREAD

**Issue by sethwarsh** [RuudBurger/CouchPotatoServer#5716]
### Steps to reproduce:
1.addd Scene Access as Provider
2 add any movie
3 Maybe an issue isolated to my installation if so please help me resolve

### Information:
Movie(s) I have this with: Legend
Quality of the movie being searched: 720 +
Providers I use:  Scene Access
Version of CouchPotato: desktop: 3.0.1 new installer
Running on: OSX

### Logs:
```
11-18 20:17:11 ERROR [edia._base.providers.base] Failed to login SceneAccess: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/_base/providers/base.py", line 159, in login
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/plugins/base.py", line 215, in urlopen
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/sessions.py", line 469, in request
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/sessions.py", line 577, in send
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/adapters.py", line 371, in send
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
TypeError: __str__ returned non-string (type Error)
 
```

**Comment by sethwarsh** [comment]
I have the same issue with Pass the Popcorn all other providers work & I have every one of them. I will submit a ticket for pass the popcorn momenteraly. Please help me resolve this issue, I can allow remote access to my system if you think it's an isolated incident. Thank you very much.

Seth

**Comment by sethwarsh** [comment]
Here is a more complete debug log:

11-19 09:45:08
INFO
[core.media.movie.searcher] Trying next release for: Legend
11-19 09:45:08
DEBUG
[to.core.media._base.media] Changing status for Legend
11-19 09:45:08
DEBUG
[o.core.notifications.core] Notifying frontend
11-19 09:45:08
DEBUG
[o.core.notifications.core] Done notifying frontend
11-19 09:45:08
INFO
[core.media.movie.searcher] Search for Legend in 720p
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: post https://torrentday.eu/V3/API/API.php, data: ['cata', '/browse.php?', 'search', 'jxt', 'jxw']
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://www.ilovetorrents.me/browse.php?search=%22legend%22+2015&page=0&cat=80, data: []
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://www.scenetime.com/browse.php?search=legend+2015&cat=59, data: []
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://torrentshack.me/torrents.php?action=advanced&searchstr=Legend+2015&scene=&filter_cat[300]=1, data: []
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit']
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://www.bitsoup.me/browse.php?search=%22legend%22+2015&cat=80, data: []
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://alpharatio.cc/torrents.php?action=advanced&searchstr=Legend+2015&scene=&filter_cat[7]=1, data: []
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://www.torrentbytes.net/browse.php?search=legend+2015&cat=5, data: []
11-19 09:45:08
INFO
[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=ss7343ww&username=hope&imdbid=tt3569230&internal=False, data: []
11-19 09:45:09
INFO
[hpotato.core.plugins.base] Opening url: get https://www.torrentleech.org/torrents/browse/index/query/legend/categories/13, data: []
11-19 09:45:09
DEBUG
[hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last):
SysCallError: (32, 'EPIPE')
11-19 09:45:10
DEBUG
[o.core.notifications.core] Getting messages with id: 862c7360-43c8-4c4c-98d6-7625f6e4ff98
11-19 09:45:10
DEBUG
[o.core.notifications.core] Returning for 862c7360-43c8-4c4c-98d6-7625f6e4ff98 1 messages
11-19 09:45:10
ERROR
[edia._base.providers.base] Failed to login SceneAccess: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/_base/providers/base.py", line 159, in login
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/plugins/base.py", line 215, in urlopen
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/sessions.py", line 469, in request
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/sessions.py", line 577, in send
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/adapters.py", line 371, in send
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
  File "/Applications/CouchPotato.app/appdata/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/libs/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
TypeError: __str__ returned non-string (type Error)
11-19 09:45:10
ERROR
[edia._base.providers.base] Failed to login to: SceneAccess
11-19 09:45:11
INFO
[core.media.movie.searcher] Wrong: Listen to Me Marlon 2015 LIMITED 720p BRRip x264-REMO, looking for 720p, found ['brrip']
11-19 09:45:11
INFO
[core.media.movie.searcher] Wrong: National Geographic Explorer S08E02 Legend of the Monkey God HDTV x264-SQUEAK, looking for 720p, found ['brrip']
11-19 09:45:11
INFO
[core.media.movie.searcher] Wrong: Lords of Xulima v2 0-HI2U, looking for 720p, found ['dvdrip']
11-19 09:45:11
INFO

**Comment by mallegonian** [comment]
Duplicate of #5555

**Comment by sethwarsh** [comment]
Not resolved in develop, I installed develop and still had the same issue.
