### ISSUE TITLE
Issue with renaming movie with a - (dash) in the title

### ISSUE THREAD

**Issue by tjashworth** [RuudBurger/CouchPotatoServer#5727]
### Steps to reproduce:
1. Run renamer scan after downloading Mission Impossible – Rogue Nation

### Information:
Movie(s) I have this with: Mission Impossible – Rogue Nation
Quality of the movie being searched: 1080p
Providers I use: IPTorrents
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer desktop) e9593f60 (2015-08-31 19:55:08)
Running on: Arch Linux and Windows 10

### Logs:
```
11-20 00:18:26 ERROR [tato.core.plugins.renamer] Couldn't move file "/media/data/Torrents/Completed/Movies/Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.DUAL-RK/Mission.Impossible.Rogue.Nation.2015.1080p.BluRay.x264-SPARKS.DUAL-RK.mkv" to "/media/movies/Movies/Mission Impossible – Rogue Nation (2015)/Mission Impossible – Rogue Nation (2015).mkv": Traceback (most recent call last):
  File "/usr/lib/couchpotato/couchpotato/core/plugins/renamer.py", line 837, in moveFile
    shutil.copy(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/movies/Movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation (2015).mkv'
 
```

**Comment by sea3pea0** [comment]
I get the same error during the renaming process. The folder name that is created during the renaming process ends up being: "Mission Impossible â Rogue Nation (2015)".
