### ISSUE TITLE
Latest Couch Potato fails renaming movies with swedish characters in title

### ISSUE THREAD

**Issue by Arken77** [RuudBurger/CouchPotatoServer#5803]
### Steps to reproduce:
1. Have Couch Potato get a movie with title with swedish characters like "Hur många kramar finns det i världen" for example (it will probobly be the same with other foreign characters). 
2. See Couch Potato fail to properly rename the movie and try create folder with strange characters in the folder name.

### Information:
Movie(s) I have this with: Hur många kramar finns det i världen
Quality of the movie being searched: Best
Providers I use: Kickass torrent and nzb. Problem is with the renaming afterward, movies download just fine.
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) de141aae (2015-11-17 21:32:28)
Running on: Ubuntu server 14.04.3 LTS

### Logs:
```
12-17 15:59:25 ERROR [tato.core.plugins.renamer] Couldn't move file "/share/downloads/complete/movies/Hur.manga.kramar.finns.det.i.varlden.2013.SWEDISH.720p.BluRay.x264-GNISTOR.cp(tt2846974)/Subs/Hur.manga.kramar.finns.det.i.varlden.2013.SWEDISH.720p.BluRay.x264-GNISTOR.idx" to "/share/movies/Hur m책nga kramar finns det i v채rlden (2013) 688/Hur m책nga kramar finns det i v채rlden.idx": Traceback (most recent call last):
  File "/opt/couchpotatoserver/couchpotato/core/plugins/renamer.py", line 829, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/share/movies/Hur m\xec\xb1\x85nga kramar finns det i v\xec\xb1\x84rlden (2013) 688/Hur m\xec\xb1\x85nga kramar finns det i v\xec\xb1\x84rlden.idx'
 
12-17 15:59:25 ERROR [tato.core.plugins.renamer] Failed renaming the file "Hur.manga.kramar.finns.det.i.varlden.2013.SWEDISH.720p.BluRay.x264-GNISTOR.idx" : Traceback (most recent call last):
  File "/opt/couchpotatoserver/couchpotato/core/plugins/renamer.py", line 625, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/opt/couchpotatoserver/couchpotato/core/plugins/renamer.py", line 829, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/share/movies/Hur m\xec\xb1\x85nga kramar finns det i v\xec\xb1\x84rlden (2013) 688/Hur m\xec\xb1\x85nga kramar finns det i v\xec\xb1\x84rlden.idx'
 
```

**Comment by JTarasovic** [comment]
Yeah, it seems like it's happening with unicode characters interpreted as UTF-8? I'm having the same problem with en-dash (eg Mission Impossible - Rogue Nation).

### Steps to reproduce:
1. Find a movie with en-dash
2. Download it
3. Try to rename

### Information:
Movie(s) I have this with: Mission Impossible - Rogue Nation
Quality of the movie being searched: N/A
Providers I use: NZBGeek -> sabnzbd+
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) de141aae (2015-11-17 21:32:28)
Running on: Ubuntu 15.10

### Logs:
```
12-19 10:39:15 INFO [tato.core.plugins.renamer] Moving "/home/usenet/Complete/movies/Mission.Impossible.Rogue.Nation.2015.BluRay.720p.DTS-ES.5.1.x264.dxva-FraMeSToR-Obfuscated.cp(tt2381249)/Ant2ZdUlrMFHF.mkv" to "/smb/media/Movies/Mission Impossible â Rogue Nation (2015)/Mission Impossible â Rogue Nation (2015) 720p.mkv" 
12-19 10:39:15 ERROR [tato.core.plugins.renamer] Couldn't move file "/home/usenet/Complete/movies/Mission.Impossible.Rogue.Nation.2015.BluRay.720p.DTS-ES.5.1.x264.dxva-FraMeSToR-Obfuscated.cp(tt2381249)/Ant2ZdUlrMFHF.mkv" to "/smb/media/Movies/Mission Impossible â Rogue Nation (2015)/Mission Impossible â Rogue Nation (2015) 720p.mkv": Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/plugins/renamer.py", line 829, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/smb/media/Movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation (2015) 720p.mkv'
 
12-19 10:39:15 ERROR [tato.core.plugins.renamer] Failed renaming the file "Ant2ZdUlrMFHF.mkv" : Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/plugins/renamer.py", line 625, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/opt/couchpotato/couchpotato/core/plugins/renamer.py", line 829, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/smb/media/Movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation (2015) 720p.mkv'
 
```
