### ISSUE TITLE
OMDB API breaks all the things when movie has a dash in the title

### ISSUE THREAD

**Issue by neonexus** [RuudBurger/CouchPotatoServer#5868]
### Steps to reproduce:
1. Download a movie that has a dash in the title
2. Hope that CP uses OMDBAPI.com for it's metadata. They apparently feel that the em dash (aka "long dash") has a place in API data... It's in every title I could think of! Noobs, or evil bastards?
3. Watch, as the poor renamer struggles to comprehend this strange length of pixels...
4. Drink a beer, sigh, and wish you knew Python so you could help fix the problem

### Information:
**Movie(s) I have this with:** Mission: Impossible - Rogue Nation (As opposed to "Mission: Impossible – Rogue Nation")
**Quality of the movie being searched:** 720p
**Providers I use:** a LOT
**Version of CouchPotato:** git:(RuudBurger:CouchPotatoServer master) de141aae (2015-11-17 15:32:28)
**Running on:** Synology DS414

### Logs:
```
01-01 18:11:12 ERROR [tato.core.plugins.renamer] Couldn't move file "/volume1/downloads/finished/movies/Mission.Impossible.Rogue.Nation.2015.720p.BluRay.HebSubs.x264-SPARKS-Obfuscated.cp(tt2381249)/Mission.Impossible.Rogue.Nation.2015.720p.BluRay.HebSubs.x264-SPARKS-Obfuscated.cp(tt2381249).mkv" to "/volume1/video/movies/Mission Impossible – Rogue Nation (2015)/Mission Impossible – Rogue Nation.mkv": Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 829, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/video/movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation.mkv'
 
01-01 18:11:12 ERROR [tato.core.plugins.renamer] Failed renaming the file "Mission.Impossible.Rogue.Nation.2015.720p.BluRay.HebSubs.x264-SPARKS-Obfuscated.cp(tt2381249).mkv" : Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 625, in scan
    self.moveFile(src, dst, use_default = not is_torrent or self.fileIsAdded(src, group))
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 829, in moveFile
    shutil.move(old, dest)
  File "/usr/local/python/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/volume1/video/movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation.mkv'
 
```

**Comment by neonexus** [comment]
Apparently the bots are out to get me today... Github's drone decided I wasn't human enough, and locked out my account for a bit. In-turn, looks like it confused the couch bot, cause he hasn't bothered to give me the usual lecture...
